### ISSUE TITLE
kube2iam implementation on Kubernetes cluster deployed using kops

### ISSUE THREAD

**Issue by cdelpinogeo** [jtblin/kube2iam#135]
Hello,

I was following your instructions on how to deploy kube2iam onto Kubernetes. We are having issues with our deployment of kube2iam onto our cluster. The daemonset is deployed without any issues and I run the iptables command on the workers. I then deploy the aws-cli pod example with the manifest modified to use a IAM i created and to look at a specific s3 bucket. I get an error from the pod, where it is looking for aws credentials.

I've tried playing around with the IAM roles and seeing if that was the issue, but I keep getting the same error. But then I realized that the nodes already have an IAM role attached to them. Do those need modifying or do we attach new roles to the nodes altogether? Are there different steps required for a kops deployed cluster?

Thanks.

**Comment by cdelpinogeo** [comment]
Thanks for responding @jrnt30.

- I am guessing you are referring to logging into the aws-cli pod? If so, that pod does not have the curl command installed. The kube2iam pods do not have it as well.

- I've not tried debug. This is the manifest I am using at the moment:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube2iam
  labels:
    app: kube2iam
spec:
  template:
    metadata:
      labels:
        name: kube2iam
    spec:
      hostNetwork: true
      containers:
        - image: jtblin/kube2iam:latest
          name: kube2iam
          args:
            - "--base-role-arn=arn:aws:iam::XXXXXXXXXXXXX:role/"
            - "--node=$(NODE_NAME)"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8181
              hostPort: 8181
              name: http
```
- I just noticed the logs on the pod, I am seeing this:
```

time="2018-05-02T18:48:06Z" level=info msg="Listening on port 8181"
time="2018-05-02T18:49:06Z" level=info msg="GET /latest/meta-data/iam/security-credentials/ (200) took 18153 ns" req.method=GET req.path=/latest/meta-data/iam/security-credentials/ req.remote=100.96.3.10 res.duration=18153 res.status=200
time="2018-05-02T18:49:06Z" level=error msg="Error assuming role AccessDenied: User: arn:aws:sts::XXXXXXXXXXXX:assumed-role/nodes.test1.XXXXXXXXXXXX.com/i-XXXXXXX is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::XXXXXXXX:role/kube-worker-ec2\n\tstatus code: 403, request id: XXXXXXXXXX" ns.name=default pod.iam.role="arn:aws:iam::XXXXXXXX:role/kube-worker-ec2" req.method=GET req.path=/latest/meta-data/iam/security-credentials/kube-worker-ec2 req.remote=100.96.3.10
time="2018-05-02T18:49:06Z" level=info msg="GET /latest/meta-data/iam/security-credentials/kube-worker-ec2 (500) took 107557617 ns" req.method=GET req.path=/latest/meta-data/iam/security-credentials/kube-worker-ec2 req.remote=100.96.3.10 res.duration=107557617 res.status=500
```
Is the issue with the attached IAM role on the workers?
