### ISSUE TITLE
kube2iam helm chart

### ISSUE THREAD

**Issue by cdelpinogeo** [jtblin/kube2iam#142]
Hi there,

I was wondering if anyone has information on the the helm chart for kube2iam:

https://github.com/kubernetes/charts/tree/master/stable/kube2iam

I am having issues deploying this onto our cluster. Not sure if I am right to open the issue here? Here is what I am doing:

- I originally used kube2iam before on a kops deployed kubernetes cluster.
- I am looking at the helm chart to deploy kube2iam to a similar cluster.
- Here is the command I am using:
```
helm install stable/kube2iam --name my-k2iam --set=extraArgs.base-role-arn=arn:aws:iam::01234567890:role/,host.iptables=true,host.interface=cbr0,image.tag=latest
```
- I then deploy the following that I use to list s3 buckets:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aws-cli
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: kube-s3
      labels:
        app: aws-cli
    spec:
      containers:
      - name: aws-cli
        image: fstab/aws-cli
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
```
- When I type in `aws s3 ls`, it asks for credentials. I then see this in the logs:
```
time="2018-05-31T14:31:59Z" level=error msg="Error assuming role AccessDenied: User: arn:aws:sts::XXXXXXX:assumed-role/nodes.test2.XXXXXX.com/i-0117d6c6ed3f9b1f5 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::XXXXXXX:role/kube-s3\n\tstatus code: 403, request id: 6093e669-64df-11e8-9a91-316598914ca9" ns.name=default pod.iam.role="arn:aws:iam::XXXXXXX:role/kube-s3" req.method=GET req.path=/latest/meta-data/iam/security-credentials/kube-s3 req.remote=100.96.4.3
time="2018-05-31T14:31:59Z" level=info msg="GET /latest/meta-data/iam/security-credentials/kube-s3 (500) took 20042917 ns" req.method=GET req.path=/latest/meta-data/iam/security-credentials/kube-s3 req.remote=100.96.4.3 res.duration=20042917 res.status=500
```
Not sure of the issue lies with the IAM role or IP tables. Thanks.
