### ISSUE TITLE
level=fatal msg="--host-ip must be set"

### ISSUE THREAD

**Issue by prudhvich92** [jtblin/kube2iam#181]
kube2iam pods are going into "crashloopbackoff" state because host ip could not set and this is happening a day after creation of the kubernetes cluster.
![screen shot 2019-01-02 at 3 04 00 pm](https://user-images.githubusercontent.com/38674420/50610113-c89f9000-0e9f-11e9-8bd7-4fe247b4e1ea.png)

**Comment by SharpEdgeMarshall** [comment]
What are you passing as `--host-ip` argument?
Should be something like this
```
spec:
      hostNetwork: true
      containers:
        - image: jtblin/kube2iam:latest
          name: kube2iam
          args:
            - "--base-role-arn=arn:aws:iam::123456789012:role/"
            - "--iptables=true"
            - "--host-ip=$(HOST_IP)"
            - "--node=$(NODE_NAME)"
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8181
              hostPort: 8181
              name: http
          securityContext:
            privileged: true
```
