### ISSUE TITLE
kube2iam installing but not working as it should be

### ISSUE THREAD

**Issue by ahsannaseem** [jtblin/kube2iam#183]
Heres how I tried deploying and using kube2iam

created 2 roles in IAM:
1) main-role
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "sts:AssumeRole"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
```

2) deployment-role(trust-relationship-policy):
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::<account_number>:role/main-role"
      },
      "Action": "sts:AssumeRole"
    },
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

Once this is done I install `kube2iam` using helm: 

> helm install stable/kube2iam --namespace kube-system --name kube2iamtesting --set=extraArgs.base-role-arn=arn:aws:iam::<account_number>:role/,extraArgs.default-role=main-role=true,rbac.create=true

Once its done I try to create deployment with `iam.amazonaws.com/role` annotation. 

```
apiVersion: v1
data:
  JDBC_CONNECTION_STRING: ''
kind: ConfigMap
metadata:
  name: env-variables
  namespace: ns-temp

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: temp-service
  name: temp-service-deployment
  namespace: ns-temp
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::<account_number>:role/deployment-role
      labels:
        app: temp-service-deployment
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: env-variables
        image: image-repo/image-tag
        name: temp-pod
        ports:
        - containerPort: 8080
          name: tempport
        resources:
          limits:
            cpu: 700m
            memory: 1.8Gi
          requests:
            cpu: 500m
            memory: 1.7Gi
```

Now when I try testing which role its assume: 

> kubectl -n ns-temp exec -it temp-service-deployment-6b879fc7cf-ln9x4 -- curl http://169.254.169.254/latest/meta-data/iam/security-credentials/

it returns:
`main-role` 

Now I am unable to identify the problem most of the docs over the internet have same mechanism to use kube2iam however for me its not seems the case. I also didnt rely on curl command but tried adding and removing permissions to role and it work only when i do changes in `main-role`, `deployment-role` have no impact on pod. 

I am running kubernetes version `1.9.x` and kube2iam `v0.9.1`
