### ISSUE TITLE
iptables not set in CoreOS

### ISSUE THREAD

**Issue by alexouzounis** [jtblin/kube2iam#20]
kube2iam appears to not print any errors but the iptables rule is not created.
Spec file is:

```
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube2iam
  labels:
    app: kube2iam
spec:
  template:
    metadata:
      labels:
        name: kube2iam
    spec:
      hostNetwork: true
      containers:
        - image: jtblin/kube2iam:latest
          name: kube2iam
          args:
            - "--base-role-arn=arn:aws:iam::123456789012:role/"
            - "--iptables=true"
            - "--host-ip=$(HOST_IP)"
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8181
              hostPort: 8181
              name: http
          securityContext:
            privileged: true
```

running the command on the terminal:

```
$ sudo iptables   --append PREROUTING   --destination 169.254.169.254   --dport 80   --in-interface docker0   --jump DNAT   --protocol tcp   --table nat   --to-destination `curl 169.254.169.254/latest/meta-data/local-ipv4`:818
```
returns:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100    13    0     0  13742      0 --:--:-- --:--:-- --:--:-- 13000
iptables v1.4.21: unknown option "--dport"
Try `iptables -h' or 'iptables --help' for more information.
```

If i move the `--protocol` flag before `--dport`, the command works as expected
