### ISSUE TITLE
Cannot use AWS Glue because of IAM pass requirements

### ISSUE THREAD

**Issue by xrl** [jtblin/kube2iam#224]
When trying to access AWS Glue from a kube2iam role I am getting the error:

I have a `k8s-jupyter` role for our scientific notebooks:

```
  jupyter:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::SECRET:role/K3NodeInstanceRole
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonAthenaFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - iam:GetRole
                  - iam:PassRole
                Effect: Allow
                Resource: arn:aws:iam::SECRET:role/AWSGlueServiceRole-*
          PolicyName: iam-pass
      RoleName: k8s-jupyter
    Type: AWS::IAM::Role
```

then in the notebook I use boto3 to interact with glue and I get this:

```
AccessDeniedException: An error occurred (AccessDeniedException) when calling the CreateCrawler operation: User: arn:aws:sts::SECRET:assumed-role/k8s-jupyter/9bfded24-k8s-jupyter is not authorized to perform: iam:PassRole on resource: arn:aws:iam::SECRET:role/service-role/AWSGlueServiceRole-datascience
```
