### ISSUE TITLE
Error assuming role AccessDenied

### ISSUE THREAD

**Issue by balusarakesh** [jtblin/kube2iam#231]
Hi,

We have the node role `k8s-worker-test` with permissions like this:
IAM policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "sts:AssumeRole"
            ],
            "Resource": "*"
        }
    ]
}

```

role for the pods: `k8s-s3-test`:

trust relationship:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    },
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::ACCOUNT_NUMBER:role:role/k8s-worker-test"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

IAM policy to list s3 buckets:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "FulfillmentReadWrite",
            "Effect": "Allow",
            "Action": [
                "s3:Get*"
            ],
            "Resource": [
                "arn:aws:s3:::S3_BUCKET_NAME"
            ]
        },
        {
            "Sid": "ListAllBuckets",
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:HeadBucket"
            ],
            "Resource": "*"
        }
    ]
}
```
Here's the config for the daemonset running the kube2iam:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube2iam
  namespace: kube-system
  labels:
    app: kube2iam
spec:
  selector:
    matchLabels:
      name: kube2iam
  template:
    metadata:
      labels:
        name: kube2iam
    spec:
      serviceAccountName: kube2iam
      hostNetwork: true
      containers:
        - image: jtblin/kube2iam:latest
          name: kube2iam
          args:
            - "--base-role-arn=arn:aws:iam::ACCOUNT_NUMBER:role/k8s-worker-test"
            - "--iptables=true"
            - "--host-ip=$(HOST_IP)"
            - "--host-interface=eni+"
            - "--verbose"
            - "--debug"
            - "--node=$(NODE_NAME)"
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8181
              hostPort: 8181
              name: http
          securityContext:
            privileged: true

```

Here's the config for the test pod container:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  labels:
    name: aws-cli
  annotations:
    iam.amazonaws.com/role: k8s-s3-test
spec:
  containers:
  - image: fstab/aws-cli
    imagePullPolicy: Always
    command:
      - /bin/sleep
    args:
      - "3600"
    env:
      - name: AWS_DEFAULT_REGION
        value: us-east-1
    name: aws-cli
```

When I run `curl 169.254.169.254/latest/meta-data/iam/security-credentials/` on the node I get `k8s-worker-test` and `k8s-s3-test` on the pod container (aws-cli).

But when I run `aws s3 ls` on the container I keep getting the following error
```
Unable to locate credentials. You can configure credentials by running "aws configure".
```
I did run `aws configure` the first time.

This is the error I see in `docker logs kube2iam_container`:
```
time="2019-09-03T15:23:40Z" level=error msg="Error assuming role AccessDenied: Access denied\n\tstatus code: 403, request id: REQUEST_ID" ns.name=default pod.iam.role="arn:aws:iam::ACCOUNT_NUMBER:role/k8s-worker-test/k8s-s3-test" req.method=GET req.path=/latest/meta-data/iam/security-credentials/k8s-s3-test req.remote=172.16.27.238
time="2019-09-03T15:23:40Z" level=info msg="GET /latest/meta-data/iam/security-credentials/k8s-s3-test (500) took 320822673.000000 ns" req.method=GET req.path=/latest/meta-data/iam/security-credentials/k8s-s3-test req.remote=172.16.27.238 res.duration=3.20822673e+08 res.status=500
```

Also note that I'm able to run `aws sts assume-role --role-arn arn:aws:iam::ACCOUNT_NUMBER:role/k8s-s3-test --role-session-name test` on the node and get credentials successfully.
