### ISSUE TITLE
Pod: FailedScheduling, 1 pod always in pending state

### ISSUE THREAD

**Issue by luvpreetsingh** [jtblin/kube2iam#243]
### Description

I am installing kube2iam using helm. Below is my installation method,

```
ubuntu@ip-172-31-30-48:~$ cat kube2iam.config.yaml
aws:
  region: "ap-south-1"

host:
  ip: $(HOST_IP)
  iptables: true
  interface: eni+
  port: 34609

extraArgs:
  auto-discover-base-arn: true
  auto-discover-default-role: true
  node: "$(NODE_NAME)"

ubuntu@ip-172-31-30-48:~$ helm install stable/kube2iam --generate-name --namespace kube-system -f ./kube2iam.config.yaml
```

I have 2 worker nodes. 1 Pod is launched successfully but 1 always remains in the pending state.

```
ubuntu@ip-172-31-30-48:~$ kubectl get pods -n kube-system | grep kube2iam
kube2iam-1575356073-kube2iam-cdtll        0/1     Pending   0          20m
kube2iam-1575356073-kube2iam-pxjkd        1/1     Running   0          167m
```

```
ubuntu@ip-172-31-30-48:~$ kubectl describe pod kube2iam-1575356073-kube2iam-cdtll -n kube-system
Name:               kube2iam-1575356073-kube2iam-cdtll
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             app.kubernetes.io/instance=kube2iam-1575356073
                    app.kubernetes.io/name=kube2iam
                    controller-revision-hash=5c766fdc54
                    pod-template-generation=1
Annotations:        kubernetes.io/psp: eks.privileged
Status:             Pending
IP:
Controlled By:      DaemonSet/kube2iam-1575356073-kube2iam
Containers:
  kube2iam:
    Image:      jtblin/kube2iam:0.10.7
    Port:       34609/TCP
    Host Port:  34609/TCP
    Args:
      --host-interface=eni+
      --node=$(NODE_NAME)
      --host-ip=$(HOST_IP)
      --iptables=true
      --auto-discover-base-arn=true
      --auto-discover-default-role=true
      --node=$(NODE_NAME)
      --app-port=34609
      --metrics-port=34609
    Liveness:  http-get http://:34609/healthz delay=30s timeout=1s period=5s #success=1 #failure=3
    Environment:
      HOST_IP:              (v1:status.podIP)
      NODE_NAME:            (v1:spec.nodeName)
      AWS_DEFAULT_REGION:  ap-south-1
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-b7mn6 (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  default-token-b7mn6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-b7mn6
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  54s (x24 over 22m)  default-scheduler  0/2 nodes are available: 1 Insufficient pods, 1 node(s) didn't have free ports for the requested pod ports, 1 node(s) didn't match node selector.
```

Any help with this?

EDIT 1:

Using,

AWS EKS Version: 1.13
Worker Node AMI: EKS Kubernetes Worker AMI with AmazonLinux2 image (k8s: 1.13.7, docker:18.06)

**Comment by luvpreetsingh** [comment]
I tried the same without helm, with the use of yaml file given in the README here,

Here is my yaml file,

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: v2-kube2iam
  labels:
    app: v2-kube2iam
spec:
  selector:
    matchLabels:
      name: v2-kube2iam
  template:
    metadata:
      labels:
        name: v2-kube2iam
    spec:
      hostNetwork: true
      containers:
        - image: jtblin/kube2iam:latest
          name: kube2iam
          args:
            - "--auto-discover-base-arn=true"
            - "--iptables=true"
            - "--auto-discover-default-role=true"
            - "--host-ip=$(HOST_IP)"
            - "--node=$(NODE_NAME)"
            - "--host-interface=eni+"
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8383
              hostPort: 8383
              name: http
          securityContext:
            privileged: true
```

I am getting the same error here,

```
ubuntu@ip-172-31-30-48:~$ kubectl get pods | grep kube2iam
v2-kube2iam-2ln59                     1/1     Running            0          13s
v2-kube2iam-ngd9q                     0/1     Pending            0          13s
```

Here is the description of the pending pod,


```
Name:               v2-kube2iam-ngd9q
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             controller-revision-hash=69dcd9df99
                    name=v2-kube2iam
                    pod-template-generation=2
Annotations:        kubernetes.io/psp: eks.privileged
Status:             Pending
IP:
Controlled By:      DaemonSet/v2-kube2iam
Containers:
  kube2iam:
    Image:      jtblin/kube2iam:latest
    Port:       8383/TCP
    Host Port:  8383/TCP
    Args:
      --auto-discover-base-arn=true
      --iptables=true
      --auto-discover-default-role=true
      --host-ip=$(HOST_IP)
      --node=$(NODE_NAME)
      --host-interface=eni+
    Environment:
      HOST_IP:     (v1:status.podIP)
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-h4tpf (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  default-token-h4tpf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-h4tpf
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  21s   default-scheduler  0/2 nodes are available: 1 Insufficient pods, 1 node(s) didn't match node selector.
  Warning  FailedScheduling  21s   default-scheduler  0/2 nodes are available: 1 Insufficient pods, 1 node(s) didn't have free ports for the requested pod ports, 1 node(s) didn't match node selector.
```
