### ISSUE TITLE
Unable to use kube2iam with roles

### ISSUE THREAD

**Issue by ahmedfourti** [jtblin/kube2iam#275]
Hello,

I am running kubernetes cluster on EC2 instance using Rancher/
I tried to use Kube2IAM but got following errors when using  `curl 169.254.169.254/latest/meta-data/iam/security-credentials/
`
`pod with specificed IP not found `

And on Kube2IAM pod I have this error

`time="2020-07-07T16:31:25Z" level=info msg="GET /latest/meta-data/iam/security-credentials/ (404) took 2044.925011 ms" req.method=GET req.path=/latest/meta-data/iam/security-credentials/ req.remote=10.42.5.13 res.duration=2044.925011 res.status=404`

Here is my config:

DaemonSet with Roles

``` 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube2iam
  namespace: kube-system

---
apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: kube2iam
    rules:
      - apiGroups: [""]
        resources: ["namespaces","pods"]
        verbs: ["get","watch","list"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: kube2iam
    subjects:
      - kind: ServiceAccount
        name: kube2iam
        namespace: kube-system
    roleRef:
      kind: ClusterRole
      name: kube2iam
      apiGroup: rbac.authorization.k8s.io
kind: List
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube2iam
  namespace: kube-system
  labels:
    app: kube2iam
spec:
  selector:
    matchLabels:
      name: kube2iam
  template:
    metadata:
      labels:
        name: kube2iam
    spec:
      serviceAccountName: kube2iam
      hostNetwork: true
      containers:
        - image: jtblin/kube2iam:latest
          imagePullPolicy: Always
          name: kube2iam
          args:
            - "--app-port=8585"
            - "--metrics-port=8585"
            - "--auto-discover-base-arn"
            - "--auto-discover-default-role=true"
            - "--iptables=true"
            - "--host-ip=$(HOST_IP)"
            - "--node=$(NODE_NAME)"
            - "--host-interface=cali+"
            - "--verbose"
            - "--debug"
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8585
              hostPort: 8585
              name: http
          securityContext:
            privileged: true

```

And here is my pod for testing

```
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  labels:
    name: aws-cli
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::123456789:role/kube2IAM_Temp
spec:
  containers:
    - image: nginx
      name: aws-cli
```

My kube2IAM_Temp sts looks like this :

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    },
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::1234567890:role/worker-role"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

And my worker role sts has the following policy

```
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "sts:AssumeRole"
            ],
            "Resource": [
                "*"
            ]
        }
```

When I use aws cli : `aws s3 ls ` I got `Unable to locate credentials. You can configure credentials by running "aws configure".`
On kube2IAm pod i have following error :

```
time="2020-07-07T16:41:41Z" level=debug msg="Proxy ec2 metadata request" metadata.url=169.254.169.254 req.method=PUT req.path=/latest/api/token req.remote=10.42.5.13
time="2020-07-07T16:41:41Z" level=info msg="PUT /latest/api/token (403) took 0.724480 ms" req.method=PUT req.path=/latest/api/token req.remote=10.42.5.13 res.duration=0.72448 res.status=403
time="2020-07-07T16:41:41Z" level=debug msg="Proxy ec2 metadata request" metadata.url=169.254.169.254 req.method=GET req.path=/latest/meta-data/placement/availability-zone/ req.remote=10.42.5.13
time="2020-07-07T16:41:41Z" level=info msg="GET /latest/meta-data/placement/availability-zone/ (200) took 0.811636 ms" req.method=GET req.path=/latest/meta-data/placement/availability-zone/ req.remote=10.42.5.13 res.duration=0.811636 res.status=200
time="2020-07-07T16:41:41Z" level=debug msg="Proxy ec2 metadata request" metadata.url=169.254.169.254 req.method=PUT req.path=/latest/api/token req.remote=10.42.5.13
time="2020-07-07T16:41:41Z" level=info msg="PUT /latest/api/token (403) took 0.829146 ms" req.method=PUT req.path=/latest/api/token req.remote=10.42.5.13 res.duration=0.829146 res.status=403
time="2020-07-07T16:41:43Z" level=info msg="GET /latest/meta-data/iam/security-credentials/ (404) took 2267.438242 ms" req.method=GET req.path=/latest/meta-data/iam/security-credentials/ req.remote=10.42.5.13 res.duration=2267.4382419999997 res.status=404

```
