### ISSUE TITLE
`hostPort` missing in helm chart

### ISSUE THREAD

**Issue by wc-s** [jtblin/kube2iam#299]
In the README.md documentation, the kube2iam container always has the `hostPort` being set, ie.
```
apiVersion: apps/v1
kind: DaemonSet
...
spec:
  ...
  template:
    ...
    spec:
      hostNetwork: true
      containers:
        - image: jtblin/kube2iam:latest
          name: kube2iam
          ...
          ports:
            - containerPort: 8181
              hostPort: 8181
              name: http
          ...
```

However, this field is impossible to configure using the helm chart: https://github.com/jtblin/kube2iam/blob/master/charts/kube2iam/templates/daemonset.yaml#L86

Am I right in saying that `hostPort` is necessary, especially if using `--iptales=true`?

If it is always necessary, I'll submit a PR adding
```
              hostPort: {{ .Values.host.port }}
```

If it is sometimes necessary and sometimes not, then someone more knowledgeable than me about kube2iam may have to add the right conditional logic to the helm chart to dynamically configure that field.
