### ISSUE TITLE
Ability to provide the external-id via a secret

### ISSUE THREAD

**Issue by costimuraru** [jtblin/kube2iam#301]
Currently, it's possible to specify an optional ExternalId, which will be used as part of the assume role, to increase security.
The external-id can only be provided via an annotation at this moment.

```yaml
  annotations:
    iam.amazonaws.com/role: role-arn
    iam.amazonaws.com/external-id: external-id
```

Given that the desire is to keep this ExternalId opaque, we would like to avoid exposing its value in the kubernetes manifest, in our CI/CD tool (Spinnaker). As such, it would increase security if we would be able to somehow provide this via a secret. Any ideas?
