### ISSUE TITLE
How to use kube2iam on self hosted cluster 

### ISSUE THREAD

**Issue by jyotibhanot** [jtblin/kube2iam#362]
I have a self hosted cluster on baremetal servers with calico as a CNI. I also have AWS account where I have created the user with specific permissions.

This is what my values.yaml looks like

```
rbac:
  create: true

aws:
  # AWS region
  region: <AWS_REGION>

host:
  # Host interface configuration
  interface: "cali+"
```
Is there some way I can use my user to assume the roles created for microservices in pod.

What is the best method to use IAM roles in self hosted cluster.
