### ISSUE TITLE
Set annotation on ReplicaSet/Deployment level

### ISSUE THREAD

**Issue by mirague** [jtblin/kube2iam#49]
Right now I'm trying to set-up `kube2iam` but I can't seem to get it working. First of all the Pods are created automatically (using [Deis Workflow](https://deis.com/docs/workflow/)), which means I cannot annotate them through a file.

Would it be possible to request the role on a Deployment/ReplicaSet/Service level? It could pass the annotation down to pods within.

**Comment by jtblin** [comment]
@mirague I think you can add the annotations in the pod template of the deployment, see example in https://github.com/kubernetes/kubernetes/issues/37666

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        mycustom: annotation
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.1
        ports:
        - containerPort: 80
```
