### ISSUE TITLE
Provide an example configuration

### ISSUE THREAD

**Issue by benbooth493** [jtblin/kube2iam#58]
I'm really struggling to fit the pieces together here. Is is possible to provide a real-world example for say listing the contents of an S3 bucket?

**Comment by jtblin** [comment]
There are several examples in the readme including one that lists the content of an s3 bucket...

**Comment by jtblin** [comment]
```
---
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  labels:
    name: aws-cli
  annotations:
    iam.amazonaws.com/role: role-name
spec:
  containers:
  - image: fstab/aws-cli
    command:
      - "/home/aws/aws/env/bin/aws"
      - "s3"
      - "ls"
      - "some-bucket"
    name: aws-cli
```
