### ISSUE TITLE
The 'base-role-arn' argument or 'auto-discover-base-arn' needs to be passed explicitly

### ISSUE THREAD

**Issue by saugup-12** [jtblin/kube2iam#70]
When defining the specs for kube2iam daemonset , the ‘base-role-arn’ not able to correctly find the base arn. However when we explicitly define ‘--auto-discover-base-arn ’, then it seems to work fine.

As per the document, 
> Either set the base-role-arn option to apply to all roles and only pass the role name in the iam.amazonaws.com/role annotation, otherwise pass the full role ARN in the annotation.

We initially had the daemonset.yml defined as :
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube2iam
  labels:
    app: kube2iam
spec:
  template:
    metadata:
      labels:
        name: kube2iam
    spec:
      hostNetwork: true
      containers:
        - image: jtblin/kube2iam:0.5.2
          name: kube2iam
          args:
            - "--base-role-arn=arn:aws:iam::123456789012:role/<role-name>"
            - "--iptables=true"
            - "--host-ip=$(HOST_IP)"
            - "--host-interface=weave"
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          securityContext:
            privileged: true
          ports:
             - containerPort: 8181
               hostPort: 8181
               name: http
```

However this did not seem to work as expected , and our aws-cli pod was not able to access the s3 bucket. The aws-cli pod definition is:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  labels:
    name: aws-cli
  annotations:
    iam.amazonaws.com/role: Kube2IAMTest
spec:
  containers:
  - image: fstab/aws-cli
    command:
      - "/home/aws/aws/env/bin/aws"
      - "s3"
      - "ls"
      - "kube2iam-test-bucket"	
    name: aws-cli
  restartPolicy: Never
```
As it can be seen that we have passed the full role-ARN in the annotations as 'iam.amazonaws.com/role: Kube2IAMTest', however it does not work.

When we changed the daemonset file definition and added '--auto-discover-base-arn' argument, then it seems to be able to discover the base-arn and work correctly. 

The new daemonset file is 
```
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube2iam
  labels:
    app: kube2iam
spec:
  template:
    metadata:
      labels:
        name: kube2iam
    spec:
      hostNetwork: true
      containers:
        - image: jtblin/kube2iam:0.5.2
          name: kube2iam
          args:
            - "--auto-discover-base-arn"
            - "--iptables=true"
            - "--host-ip=$(HOST_IP)"
            - "--host-interface=weave"
            - "--verbose"
            - "--debug"
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          securityContext:
            privileged: true
          ports:
             - containerPort: 8181
               hostPort: 8181
               name: http
```
