### ISSUE TITLE
Incorrect values for  '--base-role-arn'  do not throw proper exception

### ISSUE THREAD

**Issue by saugup-12** [jtblin/kube2iam#71]
When defining the values for kube2iam daemonset , if there is a incorrect value being passed to the '-base-role-arn', it takes the incorrect value and set it against the base-arn.There is no proper exception or error message that the value passed is invalid or incorrect.

We have defined the daemonset.yml file as:
```
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube2iam
  labels:
    app: kube2iam
spec:
  template:
    metadata:
      labels:
        name: kube2iam
    spec:
      hostNetwork: true
      containers:
        - image: jtblin/kube2iam:0.5.2
          name: kube2iam
          args:
            - "--base-role-arn=arn:aws:iam::123456789012:role/<role-name>"
            - "--iptables=true"
            - "--host-ip=$(HOST_IP)"
            - "--host-interface=weave"
            - "--verbose"
            - "--debug"
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          securityContext:
            privileged: true
          ports:
             - containerPort: 8181
               hostPort: 8181
               name: http

```
 While debugging we found that in this case the 'base-role-arn' was being set as `arn:aws:iam::123456789012:role/<role-name>/arn:aws:iam::123456789012:role/<role-name>' which is an invalid role-arn and hence it was not able to find the correct default ARN value for base-role.

Ideally it should have caught any incorrect value being passed for 'base-role-arn' and reported it first place, but it accepted the value as 'arn:aws:iam::123456789012:role/<role-name>' .

Not sure if we did it the wrong way or it was a default behavior for 'base-role-arn' argument, but took a lot of time for us to debug and figure it out.
